/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e9e1dc",
        "secondary-fixed-dim": "#eebd8e",
        "on-secondary-fixed": "#2c1600",
        "on-error-container": "#93000a",
        "surface-container": "#f5ece7",
        "tertiary-fixed-dim": "#c9c6c2",
        "outline-variant": "#c3c8c1",
        "on-tertiary-container": "#d1ceca",
        "on-primary": "#ffffff",
        "surface-dim": "#e1d8d4",
        "primary-fixed": "#d3e8d5",
        "on-primary-fixed": "#0e1f13",
        "tertiary-container": "#595855",
        "on-primary-fixed-variant": "#394b3d",
        "inverse-on-surface": "#f8efea",
        "primary-container": "#4a5d4e",
        "on-surface-variant": "#434843",
        "on-secondary-fixed-variant": "#61401b",
        "surface-variant": "#e9e1dc",
        tertiary: "#41413e",
        "surface-bright": "#fff8f5",
        "surface-tint": "#506354",
        "on-secondary": "#ffffff",
        primary: "#334537",
        "on-surface": "#1e1b18",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "secondary-container": "#fdcb9b",
        "secondary-fixed": "#ffdcbd",
        "on-background": "#1e1b18",
        "inverse-surface": "#34302c",
        "surface-container-low": "#fbf2ed",
        secondary: "#7c5730",
        "on-tertiary-fixed": "#1c1c19",
        "on-tertiary": "#ffffff",
        outline: "#737872",
        "inverse-primary": "#b7ccb9",
        "tertiary-fixed": "#e5e2dd",
        error: "#ba1a1a",
        "surface-container-high": "#efe6e2",
        background: "#fff8f5",
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
      },
      // الجزء اللي كان ناقص الخاصة بالمسافات والمقاسات
      spacing: {
        "margin-desktop": "64px",
        "gutter": "24px",
        "container-max": "1200px",
        "base": "8px",
        "margin-mobile": "20px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}